@url = https://8080-gold-leech-vmjmgnu3.ws-us21.gitpod.io

###
Get {{url}}/filmes

###
POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
PUT {{url}}/filmes/4
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

###
DELETE {{url}}/filmes
Content-Type: application/json

{
    "id" : "4"
}